### ISSUE TITLE
CentOS 6.X x64_86 Install Errors

### ISSUE THREAD

**Issue by rogueops** [decred/copay#19]
I followed these steps

cd copay
Install bower and grunt if you haven't already:

npm install -g bower
npm install -g grunt-cli
Build Copay:

bower install
npm install
grunt
npm start

All went well until I hit step "npm install" 

I get tons of errors during the install process

**Comment by jcvernaleo** [comment]
@gh0stshell I'll hunt down my install notes in a little bit and reply back but one thing was that copay (and insight) were both very picky about node versions so I highly recommend you use https://github.com/creationix/nvm so you always know what version you are using (again, I'll find in my notes which version I used for each piece since copay and insight needed different versions).

Also, I found I had much better luck with Debian/Ubuntu like systems than with RedHat type systems (but I also haven't really used anything in the RedHat family for anything other than testing in a long time so it might be me).  I think @alexlyp has had luck on RedHat (Fedora probably) but I might be wrong.  Either way, I'll look for the notes I had and reply back soon.

**Comment by jcvernaleo** [comment]
So I looked back and it looks like for copay I had the best luck with npm v4.2.1.  So using nvm I did:

```
nvm install v4.2.1
nvm use v4.2.1
npm install -g npm
cd copay
npm install
grunt
bower install
npm start
```

I think that was more or less the process.

**Comment by rogueops** [comment]
OK, I will try that shortly

since I got far with the original steps should I remove anything?

**Comment by rogueops** [comment]
got it working with the original steps after some tweaks, redoing the steps using the ones you listed

**Comment by rogueops** [comment]
when accessing localhost:3000 it is just blank

**Comment by rogueops** [comment]
never mind! with my nature to tinker and never give up I got it online!

**Comment by rogueops** [comment]
How can I change the port? I am new to nodejs, but learning as much as I can about it.

**Comment by rogueops** [comment]
also is this a full wallet I can run as a web site or does it need some of the decred software

**Comment by jcvernaleo** [comment]
You can change the port by setting the env variable PORT:

```
jcv@triforce copay $ PORT=3666 npm start

> copay@1.2.5-D start /home/jcv/code/decred/bitpay/copay
> node app.js

App listening on port 3666
```

**Comment by jcvernaleo** [comment]
So copay depends on both bws and insight.  You can run all of those locally (and a dcrd) if you really want a full wallet otherwise copay defaults to the ones we have up (https://mainnet.decred.org/ for insight for example).

Even if you use the public copy of copay, all file storage is using your brower's local storage and all the important javascript is only run locally, not on the server where copay runs.  So you don't gain too much by running your own local copay unless you are planning on modifying it.

**Comment by rogueops** [comment]
Last question, have the wallet running, found where to change the port rather then by CLI, now why can I not see an address of any kind to send DCR to that wallet?

**Comment by jcvernaleo** [comment]
@gh0stshell You are going to need to be a lot more specific than that since I do not understand the question.

You have copay running locally?  And were you able to create a wallet with it?  Once you have a wallet you get addresses from the 'Receive' tab on the bottom.

**Comment by rogueops** [comment]
wow I am blind, after running it and testing it by creating a wallet I did not even notice the bar below, thats what I get for viewing it on the server with low res, dam tiny windows!

**Comment by rogueops** [comment]
You can close, I think I am good and will edit it as needed, thanks for all the help and your patience!

**Comment by jcvernaleo** [comment]
Great, glad to hear it is working!
