### ISSUE TITLE
Test copay

### ISSUE THREAD

**Issue by marcopeereboom** [decred/copay#22]
Every assignee must test and ok this before COB of Aug 5.

Please add you tOK to this issue when completed.

**Comment by jcvernaleo** [comment]
At least on testnet all the major features (create wallets, restore from seed, send funds, receive funds, output csv, generate QR code, change units) work for me on Firefox.  

I did create a mainnet wallet but didn't do much beyond that for that one.

Couple of minor ui issues #24, #25, #26 but otherwise tACK from me.

**Comment by jrick** [comment]
Network fee policy in settings doesn't have any settings to actually change.  Was something supposed to be there, or can we remove it?

**Comment by jrick** [comment]
I went to the send view and clicked "send max" at the top to send everything, minus fees, to another wallet.  After entering the address, the "send" button lit up but when i clicked it, a "not valid" error was shown over the amount textbox and the entire screen was greyed as if there was supposed to be a modal error message shown, but there is no message.  Can't click on anything now since there's no way to hide the missing error message.  When I tested this, i had my settings set to use dbits instead of DCR, in case that matters.

**Comment by jrick** [comment]
![screenshot from 2016-08-04 14-38-03](https://cloud.githubusercontent.com/assets/1420313/17413927/3d06e192-5a51-11e6-9447-2565ad92c695.png)

After sending a transaction, the "success" message is not centered vertically and part of the "okay" button is hidden because of it.

**Comment by jrick** [comment]
Looks like the rendering issue is due to the scaling from the horizontal window width.  If i make my window less wide, the message slides up vertically.

**Comment by jcvernaleo** [comment]
So I retested (same set of things I did before) after @alexlyp's fixes and they look good.  So a real
OK
from me this time.

**Comment by jrick** [comment]
Everything (except for a tx item in my activity that went missing, but that seems to be due to insight bugs and is unrelated to the copay update) appears to be functional or addressed now. ok

**Comment by jolan** [comment]
Found an issue with Chrome which was promptly fixed.

Everything else that I tested like sending/receiving, restoring from seed, trying various options, etc. worked fine.

tACK

**Comment by marcopeereboom** [comment]
tok

**Comment by alexlyp** [comment]
Sync PR merged
