### ISSUE TITLE
Some words in passphrase have capital letters

### ISSUE THREAD

**Issue by hrishikeshio** [decred/copay#54]
e.g. 
![screen shot 2017-03-31 at 2 27 13 pm](https://cloud.githubusercontent.com/assets/1659870/24543721/3703da82-161e-11e7-8c2a-1f50b168a424.png)

It creates unnecessary confusion. it is not clear if the passphrase is case sensitive.

**Comment by jcvernaleo** [comment]
We use the pgp wordlist https://en.wikipedia.org/wiki/PGP_word_list so we cannot (and should not) change the words we use.  Some words are presented with capital letters, others are not so I see no reason at all why it would not be case sensitive.  Sorry, but nothing we can do in this case.

**Comment by hrishikeshio** [comment]
Then we should at least put a warning saying the words are case sensitive? @jcvernaleo

**Comment by jcvernaleo** [comment]
I don't see what would make anyone think they aren't case sensitive.

**Comment by hrishikeshio** [comment]
Well. The passphrase shown in original copay bitcoin wallet are not case sensitive. I only came to know that they are case sensitive in this case after reading your comment.
Capital words should be avoided imho, as they can create confusion such as between "I" and "l". (although I know such words are not part of this list)

It would not hurt to give a warning, as someone can easily miss this small detail and lose a lot of money.

**Comment by jcvernaleo** [comment]
As stated above, they CANNOT be avoided since we take this from the PGP wordlist.  And you cannot use the wallet without confirming that you know the seed by reentering the passphrase (where the correct capitalization is show).  And the pgpwordlist does not ever have a capital and non-capital word so even if you screw up and don't write down the words with correct capitalization it is a trivial task to figure out the correct word from the list.  So I see no possibility of losing funds.

**Comment by hrishikeshio** [comment]
I see.
