### ISSUE TITLE
Cannot be used in Edge

### ISSUE THREAD

**Issue by jrick** [decred/copay#6]
Clicking on "Get Started" shows the following exception:

http://i.imgur.com/BbESw7I.png

I can confirm the same error with Edge on Windows 10 Mobile as well, so this is not isolated to just desktop.

**Comment by jrick** [comment]
Surprisingly, it does work correctly in IE 11 (desktop), and that's using standards mode (not the backwards compat mode for earlier IE versions).

**Comment by marcopeereboom** [comment]
@jrick please talk to @alexlyp and test this on the sync branch.  See if it is fixed upstream.

**Comment by jrick** [comment]
See this now:

![image](https://cloud.githubusercontent.com/assets/1420313/17797943/03b5145e-659b-11e6-8903-eb9efe5c1131.png)

Same error as earlier but it happens later during the wallet creation process.

**Comment by alexlyp** [comment]
@dhill has found the offending code in buffer.  The fix is here: https://github.com/feross/buffer/pull/97

We were able to hotfix on production and confirmed the fix.  Unfortunately, due to node package management, we are having issues pulling in the fix without bringing along things that break functionality elsewhere.
